In [1]:
import pandas as pd

In [2]:
train = pd.read_csv("bikedata/train.csv")
print(train.shape)
train.head()

(10886, 12)


datetime  season  holiday  workingday  weather  temp   atemp  \
0  2011-01-01 00:00:00       1        0           0        1  9.84  14.395   
1  2011-01-01 01:00:00       1        0           0        1  9.02  13.635   
2  2011-01-01 02:00:00       1        0           0        1  9.02  13.635   
3  2011-01-01 03:00:00       1        0           0        1  9.84  14.395   
4  2011-01-01 04:00:00       1        0           0        1  9.84  14.395   

   humidity  windspeed  casual  registered  count  
0        81        0.0       3          13     16  
1        80        0.0       8          32     40  
2        80        0.0       5          27     32  
3        75        0.0       3          10     13  
4        75        0.0       0           1      1

In [3]:
test = pd.read_csv("bikedata/test.csv")
print(test.shape)
test.head()

(6493, 9)


datetime  season  holiday  workingday  weather   temp   atemp  \
0  2011-01-20 00:00:00       1        0           1        1  10.66  11.365   
1  2011-01-20 01:00:00       1        0           1        1  10.66  13.635   
2  2011-01-20 02:00:00       1        0           1        1  10.66  13.635   
3  2011-01-20 03:00:00       1        0           1        1  10.66  12.880   
4  2011-01-20 04:00:00       1        0           1        1  10.66  12.880   

   humidity  windspeed  
0        56    26.0027  
1        56     0.0000  
2        56     0.0000  
3        56    11.0014  
4        56    11.0014

In [4]:
train["datetime"] = pd.to_datetime(train["datetime"])

train["datetime-year"] = train["datetime"].dt.year
train["datetime-month"] = train["datetime"].dt.month
train["datetime-day"] = train["datetime"].dt.day
train["datetime-hour"] = train["datetime"].dt.hour
train["datetime-minute"] = train["datetime"].dt.minute
train["datetime-second"] = train["datetime"].dt.second

print(train.shape)
train[["datetime", "datetime-year", "datetime-month", "datetime-day", "datetime-hour", "datetime-minute", "datetime-second"]].head()

(10886, 18)


datetime  datetime-year  datetime-month  datetime-day  \
0 2011-01-01 00:00:00           2011               1             1   
1 2011-01-01 01:00:00           2011               1             1   
2 2011-01-01 02:00:00           2011               1             1   
3 2011-01-01 03:00:00           2011               1             1   
4 2011-01-01 04:00:00           2011               1             1   

   datetime-hour  datetime-minute  datetime-second  
0              0                0                0  
1              1                0                0  
2              2                0                0  
3              3                0                0  
4              4                0                0

In [6]:
test["datetime"] = pd.to_datetime(test["datetime"])

test["datetime-year"] = test["datetime"].dt.year
test["datetime-month"] = test["datetime"].dt.month
test["datetime-day"] = test["datetime"].dt.day
test["datetime-hour"] = test["datetime"].dt.hour
test["datetime-minute"] = test["datetime"].dt.minute
test["datetime-second"] = test["datetime"].dt.second

print(test.shape)
test[["datetime", "datetime-year", "datetime-month", "datetime-day", "datetime-hour", "datetime-minute", "datetime-second"]].head()

(6493, 15)


datetime  datetime-year  datetime-month  datetime-day  \
0 2011-01-20 00:00:00           2011               1            20   
1 2011-01-20 01:00:00           2011               1            20   
2 2011-01-20 02:00:00           2011               1            20   
3 2011-01-20 03:00:00           2011               1            20   
4 2011-01-20 04:00:00           2011               1            20   

   datetime-hour  datetime-minute  datetime-second  
0              0                0                0  
1              1                0                0  
2              2                0                0  
3              3                0                0  
4              4                0                0

In [7]:
%matplotlib inline
import seaborn as sns
import matplotlib.pyplot as plt

In [8]:
train["weather"].replace(4,3)
test["weather"].replace(4,3)
train["weather1"] = train["weather"] == 1
train["weather2"] = train["weather"] == 2
train["weather3"] = train["weather"] == 3

test["weather1"] = test["weather"] == 1
test["weather2"] = test["weather"] == 2
test["weather3"] = test["weather"] == 3

In [9]:
train["temp(int)"] = train["temp"].round()
train["atemp(int)"] = train["atemp"].round()
test["temp(int)"] = test["temp"].round()
test["atemp(int)"] = test["atemp"].round()

train["temp(difference)"] = train["temp(int)"] - train["atemp(int)"]
test["temp(difference)"] = test["temp(int)"] - test["atemp(int)"]

In [11]:
import numpy as np

In [12]:
train["windspeed"] = train["windspeed"].replace(0,np.NaN)
train["windspeed"] = train["windspeed"].fillna(method="ffill")
train["windspeed"] = train["windspeed"].fillna(6.9)

In [14]:
test["windspeed"] = test["windspeed"].replace(0,np.NaN)
test["windspeed"] = test["windspeed"].fillna(method="ffill")
#test["windspeed"] = test["windspeed"].fillna(6.9)
test[test["windspeed"].isnull()]

Empty DataFrame
Columns: [datetime, season, holiday, workingday, weather, temp, atemp, humidity, windspeed, datetime-year, datetime-month, datetime-day, datetime-hour, datetime-minute, datetime-second, weather1, weather2, weather3, temp(int), atemp(int), temp(difference)]
Index: []

[0 rows x 21 columns]

In [15]:
train["season1"] = train["season"] == 1
train["season2"] = train["season"] == 2
train["season3"] = train["season"] == 3
train["season4"] = train["season"] == 4

test["season1"] = test["season"] == 1
test["season2"] = test["season"] == 2
test["season3"] = test["season"] == 3
test["season4"] = test["season"] == 4

In [16]:
train["dayofweek"] = train["datetime"].dt.weekday
test["dayofweek"] = test["datetime"].dt.weekday

In [49]:
train["discomfort"] = 9 / 5 * train["temp"] - 0.55 * (1 - train["humidity"]) * (9 / 5 * train["temp"] - 26) + 32
test["discomfort"] = 9 / 5 * test["temp"] - 0.55 * (1 - test["humidity"]) * (9 / 5 * test["temp"] - 26) + 32

In [50]:
train.columns

Index(['datetime', 'season', 'holiday', 'workingday', 'weather', 'temp',
       'atemp', 'humidity', 'windspeed', 'casual', 'registered', 'count',
       'datetime-year', 'datetime-month', 'datetime-day', 'datetime-hour',
       'datetime-minute', 'datetime-second', 'weather1', 'weather2',
       'weather3', 'temp(int)', 'atemp(int)', 'temp(difference)', 'season1',
       'season2', 'season3', 'season4', 'dayofweek', 'discomfort'],
      dtype='object')

In [141]:
#for casual
feature_names_casual = ["season1","season2","season3","season4", "holiday","workingday","weather1","weather2","weather3","datetime-year","datetime-month",
                "datetime-hour","temp(difference)","humidity","windspeed","dayofweek","atemp","discomfort"]
#for register
feature_names_register = ["season1","season2","season3","season4", "holiday","workingday","weather1","weather2","weather3","datetime-year","datetime-month",
                "datetime-hour","temp(difference)","humidity","windspeed","dayofweek","atemp","discomfort"]

In [142]:
x_train_casual = train[feature_names_casual]
x_train_registered = train[feature_names_register]
x_test_casual = test[feature_names_casual]
x_test_registered = test[feature_names_register]

In [143]:
label_name1 = "casual"
label_name2 = "registered"

y_train_casual = train[label_name1]
y_train_registered = train[label_name2]
print(y_train_casual.shape)
y_train_casual.head()

(10886,)


0    3
1    8
2    5
3    3
4    0
Name: casual, dtype: int64

In [144]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(random_state = 37)
model

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=37, verbose=0, warm_start=False)

In [145]:
model.fit(x_train_casual, y_train_casual)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=37, verbose=0, warm_start=False)

In [146]:
prediction_list = model.predict(x_test_casual)
print(prediction_list.shape)
prediction_list

(6493,)


array([1.1 , 0.98, 1.06, ..., 4.5 , 4.3 , 2.99])

In [147]:
model = RandomForestRegressor(random_state = 37)
model

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=37, verbose=0, warm_start=False)

In [148]:
model.fit(x_train_registered, y_train_registered)
prediction_list1 = model.predict(x_test_registered)
print(prediction_list1.shape)
prediction_list1

(6493,)


array([ 10.07,   3.31,   5.11, ..., 134.41, 102.63,  64.66])

In [149]:
submit = pd.read_csv("bikedata/sampleSubmission.csv")

In [150]:
submit["count"] = prediction_list + prediction_list1
submit.to_csv("baseline-script.csv", index=False)

In [151]:
submit.head()

datetime  count
0  2011-01-20 00:00:00  11.17
1  2011-01-20 01:00:00   4.29
2  2011-01-20 02:00:00   6.17
3  2011-01-20 03:00:00   2.70
4  2011-01-20 04:00:00   2.33

In [110]:
from xgboost import XGBRegressor

## XGBoost는 사용하지 않음 -> 값이 음수가 나와서

In [132]:
p = XGBRegressor(n_estimators=1000)
p

XGBRegressor(base_score=None, booster=None, colsample_bylevel=None,
             colsample_bynode=None, colsample_bytree=None, gamma=None,
             gpu_id=None, importance_type='gain', interaction_constraints=None,
             learning_rate=None, max_delta_step=None, max_depth=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=1000, n_jobs=None, num_parallel_tree=None,
             objective='reg:squarederror', random_state=None, reg_alpha=None,
             reg_lambda=None, scale_pos_weight=None, subsample=None,
             tree_method=None, validate_parameters=None, verbosity=None)

In [133]:
p.fit(x_train_casual, y_train_casual)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.300000012, max_delta_step=0, max_depth=6,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=1000, n_jobs=0, num_parallel_tree=1,
             objective='reg:squarederror', random_state=0, reg_alpha=0,
             reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method='exact',
             validate_parameters=1, verbosity=None)

In [134]:
t1 = p.predict(x_test_registered)
t1

array([2.337922 , 1.3945415, 2.3210073, ..., 3.007486 , 2.844086 ,
       1.4524359], dtype=float32)

In [135]:
p = XGBRegressor(n_estimators=1000)
p

XGBRegressor(base_score=None, booster=None, colsample_bylevel=None,
             colsample_bynode=None, colsample_bytree=None, gamma=None,
             gpu_id=None, importance_type='gain', interaction_constraints=None,
             learning_rate=None, max_delta_step=None, max_depth=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=1000, n_jobs=None, num_parallel_tree=None,
             objective='reg:squarederror', random_state=None, reg_alpha=None,
             reg_lambda=None, scale_pos_weight=None, subsample=None,
             tree_method=None, validate_parameters=None, verbosity=None)

In [136]:
p.fit(x_train_registered, y_train_registered)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.300000012, max_delta_step=0, max_depth=6,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=1000, n_jobs=0, num_parallel_tree=1,
             objective='reg:squarederror', random_state=0, reg_alpha=0,
             reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method='exact',
             validate_parameters=1, verbosity=None)

In [137]:
t2 = p.predict(x_test_registered)
t2

array([11.600709 ,  5.554589 ,  2.815408 , ..., 96.74628  , 50.453598 ,
        2.5691645], dtype=float32)

In [138]:
submit = pd.read_csv("bikedata/sampleSubmission.csv")
submit["count"] = t1 + t2
submit.to_csv("baseline-script.csv", index=False)

In [139]:
submit.head()

datetime      count
0  2011-01-20 00:00:00  13.938631
1  2011-01-20 01:00:00   6.949130
2  2011-01-20 02:00:00   5.136415
3  2011-01-20 03:00:00   0.387024
4  2011-01-20 04:00:00   1.104748

In [140]:
submit[submit["count"] < 0]

datetime      count
27    2011-01-21 03:00:00 -13.521720
28    2011-01-21 04:00:00  -9.971772
52    2011-01-22 04:00:00 -24.775551
53    2011-01-22 06:00:00 -14.461514
54    2011-01-22 07:00:00 -19.151201
...                   ...        ...
5972  2012-11-21 04:00:00  -0.008954
6115  2012-11-27 03:00:00 -16.663456
6116  2012-11-27 04:00:00 -29.394852
6305  2012-12-24 02:00:00  -6.247652
6306  2012-12-24 03:00:00 -11.114595

[238 rows x 2 columns]