# numpy

In [1]:
import numpy as np

In [2]:
vector_row = np.array([1,2,3])

In [3]:
vector_column = np.array([
    [1],
    [2],
    [3]
])

In [5]:
print(type(vector_row))

<class 'numpy.ndarray'>


#### asarray는 왼쪽의 배열과 오른쪽의 배열이 같은 주소값을 가리키도록 만든다...

In [9]:
new_row = np.asarray(vector_row)
new_row is vector_row

100


In [7]:
new_row

array([1, 2, 3])

In [8]:
new_row = np.array(vector_row)
new_row is vector_row

False

#### 실제 array를 복사할 때에는 copy를 사용하는 것이 좋을 듯함.

In [11]:
matrix = np.array([
    [1,2],
    [1,2],
    [1,2]
])

#### 특정 숫자로 채워진 matrix를 만들기 위해서 full함수를 사용함

In [13]:
seven_matrix = np.full((3,2),7)

In [14]:
seven_matrix

array([[7, 7],
       [7, 7],
       [7, 7]])

#### sparse 행렬을 만들고 싶을 때에는 scipy의 sparse import 하기 -> 머신러닝에서 대용량 데이터의 원소가 대부분 0이어서..

In [15]:
from scipy import sparse

In [16]:
matrix = np.array([
    [0,0],
    [0,1],
    [3,0]
])

In [17]:
matrix_sparse  = sparse.csr_matrix(matrix)

In [18]:
matrix_sparse

<3x2 sparse matrix of type '<class 'numpy.intc'>'
	with 2 stored elements in Compressed Sparse Row format>

In [19]:
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


#### 자료구조에서 구현했던 matrix와 동일하게 구현된 듯 함..

In [20]:
matrix_large = np.array([
    [0,0,0,0,0,0,0,0,0,0],
    [0,1,0,0,0,0,0,0,0,0],
    [3,0,0,0,0,0,0,0,0,0]
])

In [21]:
matrix_large_sparse = sparse.csr_matrix(matrix_large)

In [22]:
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3


In [23]:
print(matrix_large)

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [3 0 0 0 0 0 0 0 0 0]]


In [24]:
print(matrix_large_sparse.shape)

(3, 10)


In [27]:
print(type(matrix_large_sparse.toarray())) # 기존의 spare matrix형태를 ndarray형태로 바꾸어줌

<class 'numpy.ndarray'>


In [28]:
vector = np.array([1,2,3,4,5])
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [29]:
vector[2]

3

In [30]:
matrix[1,1]

5

In [33]:
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
matrix[[0,2]] #0, 2행 선택

array([[1, 2, 3],
       [7, 8, 9]])

In [41]:
matrix[[0,2],[1,0]] # (0,1),(2,0)원소를 선택함

array([2, 7])

In [42]:
mask = matrix > 5

In [43]:
mask

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [44]:
matrix[mask]

array([6, 7, 8, 9])

In [45]:
matrix = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

In [46]:
matrix.shape

(3, 4)

In [47]:
matrix.size

12

In [48]:
matrix.ndim

2

In [49]:
print(matrix.dtype)

int32


In [50]:
matrix.itemsize

4

In [51]:
matrix.nbytes

48

In [52]:
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [53]:
add_100 = lambda i : i + 100

In [54]:
vectorized_add_100 = np.vectorize(add_100)

In [57]:
vectorized_add_100(matrix) # 꼭 lambda함수가 아니어도 가능.

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [58]:
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [59]:
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [60]:
np.max(matrix)

9

In [61]:
np.min(matrix)

1

In [62]:
np.max(matrix,axis=1)

array([3, 6, 9])

In [63]:
np.max(matrix,axis=0)

array([7, 8, 9])

In [64]:
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [65]:
np.mean(matrix)

5.0

In [66]:
np.var(matrix)

6.666666666666667

In [67]:
np.std(matrix)

2.581988897471611

In [68]:
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])

In [69]:
matrix.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [70]:
matrix.size

12

In [71]:
matrix.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [72]:
matrix.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

#### -1은 가능한 많이라는 뜻으로 사용된다.
-> matrix.reshape(1,-1)의 경우에는 하나의 row에 가능한 많은 원소들을 넣어달라는 의미로 해석된다.

In [76]:
matrix.ravel() # np.reshape(-1)과 동일하게 동작함.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [77]:
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [78]:
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [79]:
np.transpose(matrix)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [82]:
np.array([1,2,3,4,5]).T #row와 column을 바꾸는 것인데, 이 벡터는 1차원 벡터이기 때문에 불가능하다.

array([1, 2, 3, 4, 5])

In [83]:
np.array([[1,2,3,4,5]]).T

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [84]:
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [85]:
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
matrix.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### flatten과 reshape(-1)의 차이점
-> flatten은 새로운 배열을 복사하여 만든다. reshape는 원본에 영향을 받음

In [89]:
matrix = np.array([
    [1,1,1],
    [1,1,10],
    [1,1,15]
])

In [90]:
np.linalg.matrix_rank(matrix)

2

#### 행렬의 rank를 알기 위해서 linalg.matrix_rank를 사용함

In [92]:
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [94]:
np.linalg.det(matrix) # 행렬값

-9.51619735392994e-16

In [96]:
matrix.diagonal()

array([1, 5, 9])

In [105]:
matrix.diagonal(offset = 1) # 주 대각선 하나 위의 원소를 반환함

array([2, 6])

In [106]:
a = np.diag(matrix)

In [107]:
a

array([1, 5, 9])

In [108]:
np.diag(a)

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

In [109]:
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [110]:
matrix.trace()

15

In [111]:
sum(matrix.diagonal())

15

In [112]:
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [113]:
eigenvalues, eignevectors = np.linalg.eig(matrix)

In [114]:
eigenvalues

array([ 1.61168440e+01, -1.11684397e+00, -9.75918483e-16])

In [115]:
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])
np.dot(vector_a, vector_b)

32

In [116]:
vector_a.dot(vector_b)

32

In [117]:
np.random.random(3)

array([0.94645012, 0.24689647, 0.02973024])